version: '3.4'

services:
  r7p.orderservice.webapi:
    image: ${DOCKER_REGISTRY-}r7porderservicewebapi
    build:
      context: .
      dockerfile: src/OrderService/R7P.OrderService.WebApi/Dockerfile
    ports:
     - "5000:8080"
    depends_on:
     - "r7p_postgres"
    networks:
      - aspnetcoreapp-network

  r7p_postgres:
    container_name: 'postgres'
    image: postgres
    environment:      
      POSTGRES_PASSWORD: Qwerty1!
    networks:
      - aspnetcoreapp-network

  r7p.machinemanagerservice.webapi:
    image: ${DOCKER_REGISTRY-}r7p-machinemanagerservice-webapi
    build:
      context: .
      dockerfile: src/MachineManagerService/R7P.MachineManagerService.WebApi/Dockerfile
    ports:
     - "5000:8080"
    depends_on:
     - "r7p.machinemanagerservice.postgres"
    networks:
      - aspnetcoreapp-network

  r7p.machinemanagerservice.postgres:
    container_name: 'postgres'
    image: postgres
    environment:      
      POSTGRES_PASSWORD: Qwerty1!
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge